Repository qt4cg/qtspecs, pull requests merged in 2023-11, with the labels that each got.

#775 517: Reflected Christian Gruen's remarks
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#790 129 XSLT40 and SER40 changes for context item -> value
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: Propose Merge without Discussion

#792 783 XSLT: errors are raised
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#797 Edits to parse-uri()
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#800 660: Static functions, default parameters, XPST0017
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Tests Needed, Propose Merge without Discussion

#802 801: non-deterministic → nondeterministic
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#803 651: fn:log → fn:message
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#804 Minor edits, XQFO chh. 7, 8
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#806 566 A few minor fixes for parse-uri
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Bug, Propose Merge without Discussion

#813 809 Move fn:atomic-equal to section 14.2
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#823 712 Extend array:sort to align with fn:sort
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Needed, Propose Merge without Discussion

#761 554/754 Simplify the new transitive-closure function
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Propose Merge without Discussion

#719 413: Spec for CSV-related functions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#828 516 Add position argument to HOF callbacks
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Needed

#839 838 Fix collation variable references
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#842 Improve stylesheet for generating keyword tests
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Labels: XQFO, Editorial, Propose Merge without Discussion

#833 Fix the line endings, force a single lf in text files
  .editorconfig
  .gitattributes
  specifications/grammar-40/lalr/byaccj1.1/yacc.solaris
  specifications/xpath-datamodel-40/image-sources/dm-example.vsd
  specifications/xquery-40/image-sources/ProcMod-XPath.vsd
  specifications/xquery-40/image-sources/ProcMod-XQuery.vsd
  specifications/xquery-40/image-sources/types.vsd
Labels: Propose Merge without Discussion

#837 297 Deep Lookup Operator "??" and wildcard qualifier "::"
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed

#853 852 Fix typo in transitive-closure
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#857 856 Drop reference to obsolete error condition in deep-equal()
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#412 409, QT4CG-027-01: xsl:next-match
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Tests Needed
