Repository qt4cg/qtspecs, pull requests merged in 2023-09, with the labels that each got.

#619 XDM ch. 6 minor edits
  specifications/xpath-datamodel-40/src/attribute.xml
  specifications/xpath-datamodel-40/src/document.xml
  specifications/xpath-datamodel-40/src/element.xml
  specifications/xpath-datamodel-40/src/namespace.xml
  specifications/xpath-datamodel-40/src/processing-instruction.xml
  specifications/xpath-datamodel-40/src/text.xml
Labels: XDM, Editorial

#683 XQFO context/focus in/dependent functions clarification note
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial

#672 XFO minor edits, chap. 1
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial

#717 211: add capturing accumulators to XSLT
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed
