Repository qt4cg/qtspecs, pull requests merged in 2023-12, with the labels that each got.

#851 822: XQuery, XQFO: Edits (pool)
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#798 479: fn:deep-equal: Input order
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#849 847 Allow uri-structure-record keys to have empty sequence values
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#863 742 Drop xsl:function-library declaration
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#870 867 Explain defaults in function signatures
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#875 XQFO, chap. 9 minor edits
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#879 844 New sequence functions: names
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Labels: Editorial, Tests Needed, Propose Merge without Discussion

#884 862 Add explanations and examples of implausible expressions
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#896 887 - fix simple typo in example
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#881 866 Introduce and exploit new numeric-compare() function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed, Propose Merge without Discussion

#897 894 - errors in forming function items
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed, Propose Merge without Discussion

#902 900 fn:sort, array:sort: Parameter names
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#903 892 XPDY0002: Misleading examples
  specifications/xquery-40/src/expressions.xml
Labels: Editorial, Propose Merge without Discussion
