Repository qt4cg/qtspecs, pull requests merged in 2023-10, with the labels that each got.

#650 649: fix an xsl:fallback problem
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed

#751 QT4CG-048-01: xsl:mode/@as with built-in templates
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed

#659 647: schema location hints
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/conformance.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Propose Merge without Discussion

#749 653: Add string literals E".." and L".." to control entity expansion
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#762 758: XQFO minor edits 3
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#769 768: details about decode-from-uri
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#635 451: Schema compatibility
  specifications/xpath-datamodel-40/src/xdt-datatypes.xml
  specifications/xpath-datamodel-40/src/xdt-schema-app.xml
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed

#786 695: Added xref to fn:slice()
  specifications/xquery-40/src/expressions.xml
Labels: XPath, Editorial

#784 fos xsd
  specifications/xpath-functions-40/src/fos.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial

#753 65: Allow xmlns="xxx" to NOT change the default namespace for NameTests
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Tests Needed
