Repository qt4cg/qtspecs, pull requests merged in 2024-02, with the labels that each got.

#971 970 XQFO: Context item → value
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#979 966 Minor fixes to deep lookup
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#987 628 Define result order for distinct-values and duplicate-values
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion, Tests Added

#995 937 revised in light of CG feedback
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Propose Merge without Discussion

#997 830 Drop F+O appendix D.4
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#993 989 (partial) Allow char() to take integer argument
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Added

#984 959-partial Add fn:seconds function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Added

#943 187 Add FLWOR expression while clause
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQuery, Feature, Tests Added

#992 888, 963: Error handling for unsatisfied context dependencies
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#1010 1009 Examples, Return type of parse-json:fallback
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#985 720 Add lookup arrow expressions (method invocations)
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
Labels: Feature, Tests Needed

#1025 1001 Fix incorrect operator precedence in subsequence-where
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#795 655 fn:sort-with
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1028 960(partial) Recognize alternative representation of JSON null
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: Tests Added

#1022 999 Allow comments in regular expressions
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Added

#1031 1024 Change precedence of 'otherwise' operator
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion, Tests Added

#1034 QT4CG-066-xx Add note regarding absence of drop-while / skip-while
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1033 QT4CG-066-01 Add note that whitespace and comments in regexen are lexical constructs
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1032 1029 Make argument of fn:void optional
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion, Tests Added

#988 960 Pinned and labeled values
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XDM, Feature, Tests Needed
