Repository qt4cg/qtspecs, pull requests merged in 2024-11, with the labels that each got.

#1541 QT4CG-096-1 Add notes explaining EBNF notation
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1523 148 New functions to get type information
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Tests Needed

#1547 1542 Add "formal" definitions of non-primitive axes
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial

#1545 1539 New civil-timezone function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQFO, Feature, Tests Needed

#1564 1563 Fix fn:schema-type examples
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Bug, XQFO, Propose Merge without Discussion

#1562 1561 Correct the schema for XSLT 4.0
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: Bug, XSLT, Propose Merge without Discussion, Tests Added

#1559 1515 Add cross-references to map:build
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: XPath, XQuery, XSLT, Editorial, Propose Merge without Discussion

#1558 1522 Fix syntax ambiguity in patterns
  specifications/grammar-40/xpath-grammar.xml
  specifications/xslt-40/src/xslt.xml
Labels: Bug, XSLT, Propose Merge without Discussion

#1549 1534 Allow xsl:result-document/@select
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Tests Needed, Propose Merge without Discussion

#1543 Drop fn:element-number
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Tests Needed, Propose Merge without Discussion, Reversion

#1569 1567 Supply missing change metadata
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1556 1486 Editorial corrections & cleanups
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#1470 689 fn:stack-trace: replace with $err:stack-trace
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: Tests Added

#1560 1548 Clarify default for xsl:output/@indent
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Bug, XSLT, Tests Added

#1544 Allow (some) self-references in global variables
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Tests Needed

#1454 1449 Relax rules on multiple xsl:includes
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Revise, Tests Needed

#1546 1538 Add XSLT support for json-lines
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: XSLT, Enhancement, Tests Needed

#1576 1574 Mark some productions as XQuery only
  specifications/grammar-40/xpath-grammar.xml
Labels: XPath, Editorial, Propose Merge without Discussion

#1578 1493 Expand the rules for handling numbers in xml-to-json
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1580 1462 Change default for deep-equal options
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1581 69 Add default for current-merge-group $source
  specifications/xslt-40/src/function-catalog.xml
Labels: Bug, XSLT, Editorial, Propose Merge without Discussion

#1582 767 Fix reference to HTML5 spec
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Tests Needed, Propose Merge without Discussion

#1585 Update RELAX NG grammar for XSLT
  specifications/xslt-40/src/schema-for-xslt40.rnc
Labels: Propose Merge without Discussion

#1577 1491 Empty record types
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQuery, XQFO, Enhancement, Tests Needed

#1575 528bis element to map
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Tests Needed

#1597 1595 Editorial
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1600 1594 typos: dependant and repeated word
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#1601 1516(B) Fix problems with testing examples
  specifications/xpath-functions-40/src/fos.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
  specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
Labels: XQFO, Editorial, Propose Merge without Discussion, Build

#1607 1590 Drop draft current-mode function from catalog
  specifications/xslt-40/src/function-catalog.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1570 1550 Replace node-kind() with new type-of() function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1604 1593 Allow `document-node(NameTestUnion)`
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Enhancement, Tests Needed

#1599 1598 $err:stack-trace: string, please
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed

#1586 1527 Move record types into separate sections
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/merge-function-specs.xsl
Labels: XQFO, Editorial, Build

#1612 Drop diagnostic message from stylesheet
  specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
Labels: Build

#1603 1602 Editorial update to "other operations" on maps and arrays
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial
