Repository qt4cg/qtspecs, pull requests merged in 2024-09, with the labels that each got.

#1406 1399 clarify fixed-namespaces spec
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1405 1404 Change fn:invisible-xml grammar parameter to xs:string?
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#1402 Update schema for XSLT 4.0 to include agreed syntax changes
  specifications/xslt-40/src/schema-for-xslt40.xsd
Labels: XSLT, Editorial, Propose Merge without Discussion

#1400 1395 Revise rules for subtyping of choice item types
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery, Propose Merge without Discussion

#1398 1397 Add missing change log entry for constructor functions
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1390 1368 built in keywords improvements
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion, Build

#1386 1382 add error code XTSE4040
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Tests Added

#1383 1374 - allow static error for duplicate keys
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1380 1320 Attempt to resolve a bug in parse-uri
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1370 1369 fn:round: rounding-mode → mode
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1359 1346 Fix minor typos in format-number
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1353 1347 Add escape-solidus option to xml-to-json function
  specifications/xpath-functions-40/src/function-catalog.xml
  style/character-names.json
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1352 1350 Fix signature for unparsed-text-available
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1342 1339 Deprecate ordering mode declaration
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: XQuery, Tests Needed, Propose Merge without Discussion, Decluttering

#1228 – Adding the BLAKE3 hashing algorithm to fn:hash
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1409 1401 Rewrite of F+O section 20, Casting
  specifications/css/xpath-functions-40.css
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial

#1367 1321 leading lone slash
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
  style/leading-tokens.xsl
Labels: XPath, XQuery, Editorial, Tests Needed

#1358 959 fn:unix-time
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1344 1343 Drop the static typing feature
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/conformance.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQuery, Decluttering

#1425 1424 Fix typo
  specifications/xquery-40/src/back-matter.xml
Labels: Editorial, Propose Merge without Discussion

#1423 1387b Clarify parse-uri/build-uri encoding rules, and remove options
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1419 1337bis Replace a few remaining occurrences of "atomic value"
  specifications/xpath-datamodel-40/src/attribute.xml
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: Editorial, Propose Merge without Discussion

#1418 1415 Add to lists of XSLT declarations and instructions
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1417 1408 Fix reference to "function conversion rules" in XPTY0117
  specifications/xquery-40/src/errors.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1413 Dispose of action QT4CG-080-05, add absolute to parse-uri
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1412 Fix typo in uri-structure-record
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#1393 1391 Change function-annotations to return a sequence
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: XQFO, XDM, Tests Added

#1360 1348 Some grammar simplifications
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XPath, XQuery, XSLT, Editorial

#1428 1426 Add notes on endianness of CRC-32
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1441 1396 Improve presentation of grammar rules
  specifications/css/qtspecs.css
  specifications/xquery-40/src/ebnf.xml
  style/grammar2spec.xsl
  style/xmlspec-2016.xsl
Labels: Editorial, Build

#1440 1387 Another tweak to build-uri
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1414 XSLT spec abstract, introduction
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1364 1314 Change to type() syntax to fix ambiguity
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery, Tests Needed

#1432 1379 Initializing expression: Allow self references
  specifications/xquery-40/src/query-prolog.xml
Labels: Tests Needed

#1431 1372 Unknown option: FORG0013 → XPTY0004
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1447 1446 Rephrase conformance rule on xs:dateTime limits
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1444 Implement improvement to bibligraphy entry for IEEE 802.3
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#1438 1322 fn:collation-available (editorial)
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1434 1373 XQFO: Editorial
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1430 1427 Add element-number function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement, Tests Added

#1433 1422 fn:hash: Revision
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Needed

#1435 1421 fn:unix-time: Revisions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1439 1235 Function Identity: Treating function items with identical bodies
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed

#1453 Fix typo in load-xquery-module example
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial
