Repository qt4cg/qtspecs, pull requests merged in 2024-12, with the labels that each got.

#1611 1608 add dependency to fn compare
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1613 1605 csv-to-xml to return document node rather than element
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Propose Merge without Discussion, Tests Added

#1614 Fix xfunction refs in XSLT
  specifications/xslt-40/style/xslt.xsl
Labels: Propose Merge without Discussion

#1623 1615 Editorial rearrangement of "context" sections
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1596 1592 Rework rules for selecting a layout
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Tests Needed

#1626 1625 Editorial changes to notes on path expressions
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1635 Abbreviate suffixes on cross-spec links
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-40/style/xslt.xsl
  style/xsl-query-2016.xsl
Labels: Editorial, Build

#1629 1628 Clarify rules for XQuery version declaration
  specifications/xquery-40/src/query-prolog.xml
Labels: XQuery, Editorial, Tests Needed, Propose Merge without Discussion

#1641 1554-change-formal-specification-heading
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/merge-function-specs.xsl
Labels: XQFO, Editorial, Propose Merge without Discussion

#1642 1637 Add/Amend notes to fn:function-lookup
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1643 1103 Normalize line endings in CSV prior to parsing
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Tests Needed, Propose Merge without Discussion

#1653 1652 Use function markup
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Editorial, Propose Merge without Discussion

#1638 1634 Update description of decimal properties in the static context
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: XPath, XQuery, Editorial

#1633 1627 Tweaks to schema type functions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Bug, XQFO, Tests Needed

#1620 332 Add options for fn:path
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Added

#1622 1619 Specify XSLT map-for-key function
  specifications/xslt-40/src/function-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Feature, Tests Needed

#1664 1659 option conventions sequences as arrays
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Bug, XQFO, Editorial, Propose Merge without Discussion
