Repository qt4cg/qtspecs, pull requests merged in 2024-06, with the labels that each got.

#1233 517 Major edits to fn:chain, clarification only
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1230 1216 Detailed comments on math:e, sinh(), cosh(), tanh()
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Editorial, Propose Merge without Discussion

#921 920 Allow xsl:break and xsl:next-iteration within branch of xsl:switch
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Tests Needed, Propose Merge without Discussion

#956 850-partial Editorial improvements to parse-html()
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1015 1013 [XSLT] Clarify effect of accumulator capture on non-element nodes
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Tests Needed, Propose Merge without Discussion

#1181 296 Allow default-namespace=##any
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XPath, XQuery, XSLT, Feature, Tests Needed, Propose Merge without Discussion

#1249 31 Introduce "for key $k value $v in $map"
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Feature, Tests Needed, Propose Merge without Discussion

#1250 1048 Extended decimal format properties
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1256 991 Fix editorial details in fn:invisible-xml
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1260 1187 Add midpoint-rounding option to fn:round()
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1257 305 Add options parameter for parse-xml and parse-xml-fragment
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1258 1246 Revert incompatibility in json-to-xml number formatting
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Tests Needed, Reversion

#1259 1241 Add constraint to resolve node constructor ambiguity
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/ebnf.xml
Labels: Bug, XPath, XQuery, Tests Needed

#1279 1278 - line endings in unparsed-text-lines
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Reversion

#1276 QT4CG-081-03 parse-xml-[fragment]: $options should be optional
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Bug, XQFO, Editorial

#1270 QT4CG-081-01 Add cross refererence from fn:round-half-to-even
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1268 QT4CG-077-03 Add note on document order across documents
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1275 1274 Further rounding modes
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Added

#1264 1245 Correct properties of format-DT function family
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1302 Stylesheet fix for 1298
  style/xsl-query-2016.xsl
Labels: Build

#1304 Fixed typo in the example of scan-right
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1255 1253 whitespace in xsl:switch
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1292 Fix issue 1291 (rounding)
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1286 Updated list of incompatibilities in F+O
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial

#1295 1096 Redefine array:index-of to use deep-equal for comparisons
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Bug, XQFO, Tests Needed

#1288 1287 Define parse-xml error conditions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Tests Added

#1303 Recognize 'fn' as well as 'function' in signatures
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
Labels: Build
