Repository qt4cg/qtspecs, pull requests merged in 2024-03, with the labels that each got.

#1051 1043 Clarification of CSV edge cases
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1046 1038 take-while predicate no longer uses EBV
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1053 1047 Default predicate for some#1 and every#1
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Needed

#1057 1054 Spec fn:message #id using old name fn:log
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1058 1037 fn:json-to-xml: 'number-parser' option
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1066 1052 Simplify the results of parse-csv
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/schema-for-csv.xsd
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/merge-function-specs.xsl
Labels: Tests Added

#1073 XQFO (editorial)
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1080 1036 Rephrase the rules for number-parser with liberal JSON
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1081 1050 Fix ItemType grammar ambiguity
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, Editorial, Propose Merge without Discussion

#1083 1079 Change book used in example
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Editorial, Propose Merge without Discussion

#1090 1089 Add rounding rules for casting string to duration etc
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement, Propose Merge without Discussion, Tests Added

#1076 1075 Drop 'with' expressions
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion, Reversion

#1078 1060 Formatting XPath/XQuery
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/function-catalog.xml
  specifications/xslt-40/src/xml-to-json.xsl
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#1097 566-partial Fix colon issue in URI parsing
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1074 Confirm status of provisional functions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Tests Needed

#1077 Correct the status of new language features
  specifications/xquery-40/src/back-matter.xml
Labels: XPath, XQuery, Editorial

#1071 1070 Bare Brace map constructor syntax
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: XPath, XQuery, Enhancement, Blocked, Tests Added

#1106 859 lookup syntax problems
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#1092 1039 Add notes referring to fn:collation-key
  specifications/xquery-40/src/expressions.xml
Labels: XQuery, Editorial, Propose Merge without Discussion, Tests Added
