Repository qt4cg/qtspecs, pull requests merged in 2024-05, with the labels that each got.

#1186 1170 Editorial: fn:index-where
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#1182 1171 Change predicate callbacks to allow empty return value
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Added

#1184 1165-Use Unicode-style character references
  schema/xsl-query.dtd
  specifications/css/qtspecs.css
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
  style/character-names.json
  style/xsl-query-2016.xsl
Labels: XQFO, Editorial, Build

#1148 1143 Coercion rules: handle choice types before atomization
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Tests Needed

#1201 Update the Saxonica EE repo
  build.gradle
Labels: Build

#1190 1188 XQFO hash
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1200 QT4CG-075-02 Define the term sequence concatenation
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, Editorial, Propose Merge without Discussion

#1068 73 fn:graphemes
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Tests Needed

#1198 1189 distinct document order
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xslt-40/src/xslt.xml
Labels: XQFO, Enhancement, Tests Added

#1205 1196 Math Functions: math:e, math:sinh, math:cosh, math:tanh
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1206 1195 Hash Function: CRC-32
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#1220 73 copy&paste typo in fn:graphemes (combining diaeresis should be ZWJ)
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1222 1214 hash examples
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1223 Minor: fixed URL
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1117 1116 Add options param to unparsed-text
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1197 1192 Allow fn as abbreviation for function
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Enhancement, Tests Needed

#1191 1167, 934 deep equal merge collations param
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1219 1218 Drop use of union(A,B) syntax
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#1217 1207 Allow numeric predicates when filtering arrays
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Enhancement, Tests Needed

#1212 1208 correct details of formerly-reserved function names
  specifications/xquery-40/src/ebnf.xml
Labels: XQuery, Editorial, Propose Merge without Discussion

#1211 QT4CG-076-01 Add examples of coercions
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial

#1243 Change required result of system-property(...version)
  specifications/xslt-40/src/function-catalog.xml
Labels: XSLT, Propose Merge without Discussion, Tests Added

#1237 1232 consistent rendition of rfc2119 terms
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/introduction.xml
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-40/style/xslt.xsl
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
  style/xmlspec-2016.xsl
Labels: Editorial, Propose Merge without Discussion, Build
