Repository qt4cg/qtspecs, pull requests merged in 2024-01, with the labels that each got.

#901 895 Parameters with default values: allow empty sequences
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Tests Needed, Propose Merge without Discussion

#904 821 Annotations: Make default namespace explicit
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Tests Needed, Propose Merge without Discussion

#905 898 - relax the constraints on document-uri
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#907 906 fn:deep-equal: unordered → ordered
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#912 XQFO: Minor edits
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#922 915 function body terminology
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#923 913-new-examples-for-local-name-etc
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#924 648 Disallow user modifications to schema for FN namespace
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#925 780 Document incompatibility in format-number etc
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/function-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#926 860 Editorial rearrangement of spec for shallow lookup
  specifications/xquery-40/src/expressions.xml
Labels: Propose Merge without Discussion

#909 893 fn:compare: Support for arbitrary atomic types
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed

#737 295: Boost the capability of recursive record types
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Tests Needed, Propose Merge without Discussion

#932 931 Add rules for duration precision
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#933 930 drop obsolete note about comments and PIs
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#942 530 Fix typo, escape-solidus not escape-uri-attributes
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: Propose Merge without Discussion

#947 Reorganise F+O chapter 15 [editorial]
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#941 939 Remove fn:numeric-compare
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Propose Merge without Discussion

#950 Minor edits (examples, rules)
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#952 945 module import contradiction
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Propose Merge without Discussion

#958 951 Parameters with default values: fn:lang, fn:id, fn:idref, fn:element-id
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion

#937 779 hash function
  etc/rfc.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Propose for V4.0, Tests Needed

#965 XQFO: minor edits and bug fixes
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Editorial, Propose Merge without Discussion
