Repository qt4cg/qtspecs, pull requests merged in 2024-04, with the labels that each got.

#1134 1133 Correct map:filter callback signature
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Bug, Propose Merge without Discussion

#1128 1020 Further notes on the consequences of function coercion
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1123 1118 Drop the "map" keyword in adaptive serialization output
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: Enhancement, Serialization, Propose Merge without Discussion, Tests Added

#1112 1110-partial New error codes
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Tests Needed, Propose Merge without Discussion

#1132 122 Choice item types (generalizing local union types)
  specifications/grammar-40/xpath-grammar.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/xslt.xml
Labels: Feature, Tests Needed

#1131 796,231 - Extend XPath for and let expressions
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, Enhancement, Tests Added

#1149 1084 Add fos:default-description to support prose descriptions of defaults
  specifications/xpath-functions-40/src/fos.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/style/generate-keyword-test-set.xsl
  specifications/xpath-functions-40/style/merge-function-specs.xsl
Labels: Editorial, PR Pending, Propose Merge without Discussion, Build

#1156 Fix error in XSLT example
  specifications/xslt-40/src/xslt.xml
Labels: Bug, XSLT, Propose Merge without Discussion

#1151 1138 Merge format and format-name params of format-number
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Tests Needed

#1150 1142 Drop restriction disallowing items-equal with unordered
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1147 QT4CG-072-01 Clarify schema type terminology
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial

#1141 1140 Replace 'search' with 'target' for indexing functions
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1164 1155 Consistency of glossaries
  specifications/xpath-datamodel-40/style/data-model.xsl
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xslt-40/style/xslt.xsl
  style/xsl-query-2016.xsl
Labels: Editorial, Propose Merge without Discussion, Build

#1163 1159 Add filter expressions for maps and arrays
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Feature, Tests Added

#1157 1135 Correction to definition of focus functions
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery, Editorial

#1125 1094 Enhanced lookup expressions
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, Enhancement, Tests Needed

#1178 1146 Add inline change markup in the XPath/XQuery spec
  specifications/xquery-40/src/back-matter.xml
  specifications/xquery-40/src/conformance.xml
  specifications/xquery-40/src/ebnf.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/introduction.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Propose Merge without Discussion

#1174 1173 array:build, map:build: Positional access
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Tests Needed

#1087 1086 Editorial changes to array:values
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial
