Repository qt4cg/qtspecs, pull requests merged in 2025-04, with the labels that each got.

#1913 1911 Clarifications for regular expressions
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Propose Merge without Discussion

#1904 1832 Operator Associativity
  specifications/xquery-40/src/ebnf.xml
Labels: XPath, XQuery, Editorial, Propose Merge without Discussion

#1915 1902b bin:unpack out of range error
  specifications/EXPath/binary/src/binary-functions.xml
  specifications/EXPath/binary/src/function-catalog.xml
  style/xmlspec-2016.xsl
Labels: Bug, Tests Needed, EXPath

#1914 501 Error handling: try/finally
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQuery, Enhancement, Tests Needed

#1910 1021 (part 1) Add $options arg to doc() and doc-available()
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XPath, XQuery, Enhancement, Tests Needed

#1908 1520 Allow forwards references to named item types
  specifications/xquery-40/src/query-prolog.xml
Labels: Bug, XQuery, Tests Added

#1897 1876 In fn:replace(), merge the $replacement and $action parameters
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Added, In Saxon 13

#1895 1881 Function identity for maps and arrays
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1819 451 Multiple schemas in XSLT
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Feature, Tests Needed, Tests Added, In Saxon 13

#1919 1905 Editorial edits
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/function-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: Editorial, Propose Merge without Discussion

#1930 QT4-CG-116-04 correction to fn:function-identity
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1901 1363 fallback becomes a value not a function
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1918 1891 clarifications on HTML versions and errors
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement

#1931 QT4-CG-116-02 improve description of validation
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1940 1939 XQDY0153 (from try/finally) should be a type error
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed, Propose Merge without Discussion

#1929 1725 xsl:mode/@copy-namespaces
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Tests Added, In Saxon 13

#1928 1844b Arrow Expressions
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Editorial

#1926 1907 method lookup (disallow wildcard selection)
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Enhancement, Tests Needed, Propose Merge without Discussion

#1941 Add PR numbers and dates to change metadata
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Editorial, Propose Merge without Discussion

#1947 1943 Mark attributes with form=qualified
  specifications/xslt-40/src/schema-for-xslt40.xsd
Labels: Bug, XSLT

#1906 1797 elements-to-maps-conversion-plan function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement, Propose Merge without Discussion, Tests Added, In Saxon 13

#1950 1704 Add rules/notes for BOM and related topics
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1587 557 Add fn:unparsed-binary function
  specifications/xpath-functions-40/src/fos.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
Labels: XQFO, Feature, Tests Needed

#1933 1271 fn:xsd-validator() function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  style/character-names.json
Labels: XQFO, Enhancement, Tests Needed

#1956 1954 (part) Private variables and functions don't need to be in the module namespace
  specifications/xquery-40/src/query-prolog.xml
Labels: XQuery, Enhancement, Tests Needed

#1966 1568b Add unicode case-blind collation
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement, Tests Added, In Saxon 13
