Repository qt4cg/qtspecs, pull requests merged in 2025-01, with the labels that each got.

#1663 Remove DTD/stylesheet distractions at the top of the schema
  specifications/xslt-40/src/schema-for-xslt40.xsd
Labels: XSLT, Editorial, Propose Merge without Discussion

#1665 1650 Tidy up fn:type-of
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1666 1649 result of function annotations
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Bug, XQFO, Propose Merge without Discussion, Tests Added

#1668 Minor copy edits (no issue raised)
  specifications/xpath-functions-40/src/fos.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/merge-function-specs.xsl
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQFO, Editorial, Propose Merge without Discussion, Build

#1669 1667 Revise handling of non-XML characters in parse-json
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1670 Action QT4CS-097-02: Enable xtermref links to XSD SCM property names
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  style/xsl-query-2016.xsl
Labels: Editorial, Propose Merge without Discussion, Build

#1679 1678 Define element(E,T) and attribute(A,T) in terms of "derives-from"
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery

#1676 1621 Capabilities of Collations
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Editorial, Enhancement, Tests Needed

#1674 1662 Allow composite sort keys in xsl:sort
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Tests Needed

#1671 1261 New fn:divide-decimals() function
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Tests Added

#1691 1681 - Delta marker in TOC
  specifications/css/w3c-base.css
Labels: Build

#1673 1407 TOC structure for types
  specifications/xpath-functions-40/style/xpath-functions.xsl
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/style/diff.xsl
  specifications/xslt-40/style/xslt-diff.xsl
  specifications/xslt-40/style/xslt.xsl
  style/xmlspec-2016.xsl
Labels: XPath, XQuery, XQFO, Editorial, Propose Merge without Discussion

#1677 1675 Fixes for CSV parsing
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: Bug, XQFO

#1690 1688 In "implementation-defined" appendix, fix absent generated link
  specifications/xpath-functions-40/style/xpath-functions.xsl
Labels: Propose Merge without Discussion, Build

#1693 1683 Extend xpath-functions schema with CSV components
  specifications/xpath-functions-40/src/xpath-functions.xsd
  specifications/xpath-functions-40/style/generate-qt3-test-set.xsl
Labels: Propose Merge without Discussion, Build

#1695 1284 Define streamability of distinct-ordered-nodes
  specifications/xslt-40/src/xslt.xml
Labels: Bug, XSLT, Tests Needed, Propose Merge without Discussion

#1692 1680 Fix switch syntax ambiguity
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XQuery, Tests Needed

#1707 Fix bug in build dependencies
  build.gradle
Labels: Build

#1700 Remove some dead .DS_Store files
  schema/common/.DS_Store
  schema/common/mathml/.DS_Store
  schema/common/mathml/mathml1/.DS_Store
  schema/common/mathml/mathml2/.DS_Store
  schema/common/mathml/mathml2/html/.DS_Store
  schema/common/mathml/mathml2/iso8879/.DS_Store
  schema/common/mathml/mathml2/iso9573-13/.DS_Store
  schema/common/mathml/mathml2/mathml/.DS_Store
  schema/common/mathml/mathml3/.DS_Store
  schema/common/rddl/.DS_Store
  schema/common/svg10/.DS_Store
  schema/common/svg11/.DS_Store
  schema/common/svg11/templates/.DS_Store
  schema/common/xhtml10/.DS_Store
  schema/common/xhtml11/.DS_Store
  schema/common/xmlschema/.DS_Store
  schema/common/xmlspec/.DS_Store
Labels: Propose Merge without Discussion, Build

#1710 1709 Updated type diagrams
  specifications/image-sources/anyAtomicType.xml
  specifications/image-sources/anyType.xml
  specifications/image-sources/item-types.xml
  specifications/xslt-40/schema/xsltspec.dtd
  specifications/xslt-40/src/xslt.xml
Labels: XQFO, XDM, Editorial, Propose Merge without Discussion

#1711 1705 Say that max precision is implementation-defined
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1686 1685 Pipeline Operator
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Tests Needed

#1712 1706 Drop "else if" and "else" clauses from braced conditionals
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery, Tests Needed, Reversion

#1703 1651 ordered maps
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.rnc
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
  specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Labels: XPath, XQuery, XSLT, XQFO, XDM, Feature, Tests Needed

#1728 Fix CSS for production tables
  specifications/css/qtspecs.css
Labels: Propose Merge without Discussion, Build

#1732 1720 grammar simplification
  specifications/grammar-40/grammar.dtd
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
  style/assemble-spec.xsl
  style/grammar2spec.xsl
Labels: Editorial, Propose Merge without Discussion, Build, Decluttering

#1708 1485 Add xsl:record-type declaration
  specifications/xquery-40/src/expressions.xml
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Feature, Tests Needed

#1727 1725 Define more detailed rules for duplicates in maps
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XSLT, XQFO, Enhancement, Tests Needed

#1731 1719 drop shared spec from build
  build.gradle
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xpath-functions-40/style/xpath-functions-30.xsl
  specifications/xquery-40/build-shared.xml
  specifications/xquery-40/src/XPathXQueryShared.xml
  specifications/xquery-40/style/shared.xsl
  style/xmlspec-override.xsl
Labels: Propose Merge without Discussion, Build, Decluttering

#1745 Implement expanding/collapsing ToC
  build.gradle
  specifications/css/w3c-base.css
  specifications/css/xslt-40.css
  specifications/js/toc.js
  style/xmlspec-2016.xsl
Labels: Propose Merge without Discussion, Build

#1749 Don't fix the function finder on small devices
  specifications/css/xpath-functions-40.css
  specifications/css/xslt-40.css
Labels: Build
