Repository qt4cg/qtspecs, pull requests merged in 2025-03, with the labels that each got.

#1855 1771 Add option for deep-equal to consider map order
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed, Propose Merge without Discussion

#1850 Actions from meeting 111
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: Propose Merge without Discussion

#1849 Reduce the indentation in the ToC
  specifications/css/w3c-base.css
Labels: Editorial, Propose Merge without Discussion

#1839 Relax the return type of the Invisible XML parsing function
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: Propose Merge without Discussion

#1838 1820 Attempt to add change markup in collapsed ToC
  specifications/js/toc.js
  style/xmlspec-2016.xsl
Labels: Propose Merge without Discussion, Build

#1853 1845 Revised design of methods to use . rather than $this
  specifications/xquery-40/src/errors.xml
  specifications/xquery-40/src/expressions.xml
  specifications/xquery-40/src/query-prolog.xml
Labels: XPath, XQuery, Feature, Tests Needed

#1801 1798 Function fn:function-identity
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Feature, Tests Needed

#1740 1725b Further elaboration of duplicates handling in maps
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xslt-40/src/element-catalog.xml
  specifications/xslt-40/src/schema-for-xslt40.rnc
  specifications/xslt-40/src/schema-for-xslt40.xsd
  specifications/xslt-40/src/xslt.xml
Labels: XQFO, Enhancement, Tests Added

#1864 1456 Lookup expressions filtered by type
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Feature, Tests Needed

#1880 Editorial revision of fn:function-identity
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial, Propose Merge without Discussion

#1878 1851 Make ?variety optional; explain namespace-sensitive
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Propose Merge without Discussion, Tests Added

#1873 1869 duplicate values
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/style/merge-function-specs.xsl
Labels: XQFO, Enhancement, Propose Merge without Discussion, Tests Added, In Saxon 13

#1867 1341 Drop position from fold callbacks
  specifications/xpath-datamodel-40/src/xpath-datamodel.xml
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Tests Added, Reversion, In Saxon 13

#1877 1866 Disambiguate TypeSpecifier syntax
  specifications/grammar-40/xpath-grammar.xml
  specifications/xquery-40/src/expressions.xml
Labels: Bug, XPath, XQuery, Tests Needed

#1882 982 Editorial rewrite of scan-left and scan-right
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Editorial

#1879 1857, 1860: Add more options to parse-xml
  specifications/xpath-functions-40/src/function-catalog.xml
Labels: XQFO, Enhancement, Tests Needed

#1856 998 Add boundary and lookahead/behind assertions
  specifications/xpath-functions-40/src/analyze-string.xsd
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
  specifications/xslt-40/src/function-catalog.xml
  specifications/xslt-40/src/xslt.xml
Labels: XQFO, Feature, Tests Added, In Saxon 13

#1875 1861 Params passed automatically through next-match
  specifications/xslt-40/src/xslt.xml
Labels: XSLT, Enhancement, Tests Needed

#1874 1862 Coercing to a record type changes map order
  specifications/xquery-40/src/expressions.xml
Labels: XPath, XQuery, Enhancement, Tests Added

#1886 1660 Additional options for fn:path
  specifications/xpath-functions-40/src/function-catalog.xml
  specifications/xpath-functions-40/src/xpath-functions.xml
Labels: XQFO, Enhancement, Tests Needed
